config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  ActiveAdmin.routes(self)

  resources :tests do
    resources :test_results, only: %i[new create]
    resources :ratings, only: %i[create update destroy]
    resources :comments, only: :create do
      resources :comments, only: :create
    end
    get '/like', to: 'likes#like'
    get '/unlike', to: 'likes#unlike'
  end
  resources :home, only: :index
  resources :test_results, only: :index

  root to: 'home#index'
end

app/models/test_result.rb
class TestResult < ApplicationRecord
  serialize :answers, JSON

  enum state: %i[active archived]

  belongs_to :test
  belongs_to :user

  validates :user_id, :test_id, :answers, :correct_answers_count, :state,
    presence: true

  before_validation :count_correct_answers_count
  before_create :archive_previous

  private

  def count_correct_answers_count
    questions = test.try(:questions)
    return unless questions

    self.correct_answers_count = answers.inject(0) do |count, (k, v)|
      if questions[k]['correct_answer'] == v
        count + 1
      else
        count
      end
    end
  end

  def archive_previous
    previous = user.test_results.where(test_id: test_id).active
    previous.update_all(state: self.class.states[:archived])
  end
end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_action :set_test, only: %i[new create]

  def index
    @progress = UsersProgress.new(current_user.id)
  end

  def new
    @test_result = current_user.test_results.where(test: @test).build
  end

  def create
    @test_result = current_user.test_results.build(test_result_params)
    if @test_result.save
      @rating = current_user.ratings.where(test: @test).first_or_initialize
      render :congratulations
    else
      render :new
    end
  end

  private

  def set_test
    @test = Test.for_everyone.find(params[:test_id])
  end

  def test_result_params
    answers_keys = (1..Test::QUESTIONS_COUNT).map(&:to_s)
    params
      .require(:test_result)
      .permit(:question_id, :test_id, answers: answers_keys)
  end
end

app/views/test_results/_categories.html.haml
.panel-group.test-results-list
  - data.each do |(cat_id, cat_name), topics|
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          %a{'data-toggle': :collapse, href: "##{type}Cat#{cat_id}"}
            = cat_name
      .panel-collapse.collapse{id: "#{type}Cat#{cat_id}"}
        %ul.list-group
          - topics.each do |(topic_id, topic_name), tests|
            = render 'topics_with_tests',
              topic_id: topic_id,
              topic_name: topic_name,
              tests: tests,
              type: type

app/views/test_results/_progress_bar.html.haml
.progress
  .progress-bar{'aria-valuemax': Test::QUESTIONS_COUNT, 'aria-valuemin': 0, role: :progressbar}
    %span.answered-tests-count
    = "/ #{Test::QUESTIONS_COUNT}"

app/views/test_results/_question_tab.html.haml
.form-group
  = question.fetch('body', nil)
- 1.upto(Test::ANSWERS_COUNT) do |answer_index|
  .form-group.radio-buttons
    = radio_button_tag "test_result[answers][#{index}]",
      answer_index,
      false,
      id: "test_result_answers_#{index}_#{answer_index}",
      required: true
    = label_tag "test_result_answers_#{index}_#{answer_index}",
      (question.fetch('answers', [])[answer_index-1] || {})['body']

app/views/test_results/_question_tab_buttons.html.haml
.buttons
  - unless index.zero?
    .btn.btn-default.btnPrevious= t('.previous')
  - if index == Test::QUESTIONS_COUNT
    = form.button :submit, class: 'btn btn-primary disabled', disabled: true
  - else
    .btn.btn-default.btnNext{class: (index.zero? ? '' : 'disabled'), disabled: !index.zero?}
      = t('.next')

app/views/test_results/_topics_with_tests.html.haml
%li.list-group-item.panel
  .panel-heading
    .panel-title
      %a{'data-toggle': :collapse, href: "##{type}Topic#{topic_id}"}
        = topic_name
  .panel-collapse.collapse.test-results-list{id: "#{type}Topic#{topic_id}"}
    %table.table.table-hover
      %thead
        %tr
          %th= t('.title')
          - if type == :completed
            %th= t('.correct_answers_count')
          %th
      %tbody
        - tests.each do |data|
          %tr
            %td
              = data['test_title']
            - if type == :completed
              %td
                = "#{data['correct_answers_count']}/#{Test::QUESTIONS_COUNT}"
            %td.controll-links
              = link_to t('.start'), new_test_test_result_path(test_id: data['test_id'])

app/views/test_results/congratulations.html.haml
.page-header
  %h2= t('.title')

%p
  = t('.body',
    test_title: @test.title,
    correct_answers_count: @test_result.correct_answers_count,
    questions_count: Test::QUESTIONS_COUNT)
%div
  = t('.please_rate')
  .ratings.users-rating{'data-test-id': @test.id, 'data-score': @rating.score, 'data-rating-id': @rating.id}

%hr
= link_to t('.back_btn'), root_path, class: 'btn btn-default btn-sm'
\|
= link_to t('.again'), new_test_test_result_path(test_id: @test.id), class: 'btn btn-default btn-sm'
\|
= link_to t('.show'), @test, class: 'btn btn-default btn-sm'

app/views/test_results/index.html.haml
.page-header
  %h2= t('.page_title')

- if @progress.count_of_tests.zero?
  = t('.no_tests')
- elsif @progress.completed_tests.empty?
  = t('.have_no_completed_tests', count_of_tests: @progress.count_of_tests)
- else
  = t('.body',
    count_of_tests: @progress.count_of_tests,
    count_of_completed_tests: @progress.completed_tests.count,
    average_value_of_answers: @progress.average_value_of_answers,
    answers_count: Test::QUESTIONS_COUNT)

- if @progress.count_of_tests > 0
  %h4
    = t('.not_started_tests')
  = render 'categories', data: @progress.not_started_tests, type: :not_started

- if @progress.completed_tests.present?
  %h4
    = t('.completed_tests')
  = render 'categories', data: @progress.completed_tests, type: :completed

app/views/test_results/new.html.haml
.page-header
  %h2= @test.title

= render 'progress_bar'
= simple_form_for [@test, @test_result] do |f|
  =f.hidden_field :test_id, value: @test.id
  = tabs content_class: 'test-result-question-tab-content' do |c|
    - c.tab t('.description') do
      = @test.description
      = render 'question_tab_buttons', index: 0
    - 1.upto(Test::QUESTIONS_COUNT) do |i|
      - c.tab t('.question_tab_name', i: i) do
        = render 'question_tab',
          index: i,
          question: @test.questions.fetch(i.to_s, {}),
          disabled: false
        = render 'question_tab_buttons', index: i, form: f
%hr
= link_to t('.back_btn'), home_index_path, class: 'btn btn-default btn-sm'