config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  ActiveAdmin.routes(self)

  resources :tests do
    resources :test_results, only: %i[new create]
    resources :ratings, only: %i[create update destroy]
    resources :comments, only: :create do
      resources :comments, only: :create
    end
    get '/like', to: 'likes#like'
    get '/unlike', to: 'likes#unlike'
  end
  resources :home, only: :index
  resources :test_results, only: :index

  root to: 'home#index'
end

app/views/layouts/partials/_head.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%title= content_for?(:title) ? yield(:title) : t('general.site_name')
= csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/partials/_header.html.haml
%nav.navbar.navbar-toggleable-md.navbar-inverse.bg-inverse.fixed-top
  .navbar-toggler.navbar-toggler-right
    = link_to t('general.site_name'), root_path, class: 'navbar-brand'
  .menu
    .dropdown
      .menu-icon.dropdown-toggle.glyphicon.glyphicon-th-list{'aria-expanded': false, 'aria-haspopup': true, 'data-toggle': :dropdown, type: :button}
      %ul.dropdown-menu.pull-right
        - if current_user.admin?
          %li
            = link_to t('header.menu.admin'), admin_root_path
        %li
          = link_to t('header.menu.tests'), tests_path
        %li
          = link_to t('header.menu.progress'), test_results_path
        %li
          = link_to t('header.menu.settings'), edit_user_registration_path
        %li.divider{role: :separator}
        %li
          = link_to t('header.menu.logout'), destroy_user_session_path
    .avatar
      = users_avatar_img(current_user)